
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "library.c"


// Teleop-only "library" functions:
const int joystickZero = 7; // Joysticks are very sensitive; it may be a bit off zero when they're not trying to move anything anyway (out of 127)

// Exponential function to map to the joystickValue
int joystickToMotor(int joystickValue)
{

	int motorValue;
	const int minimumValue = 4; // This value high = less control, less whining; this value low = more fine control, more whining, more magic blue smoke (out of 100)
	if (abs(joystickValue) < joystickZero)
	{
		motorValue = 0;
	}
	else
	{
		// We will play the piccolo
		const int motorMax = 100;
		int backwards = joystickValue < 0 ? -1 : 1;
		motorValue = (pow(1.05, abs(joystickValue)) / pow(1.05, 127)
			* (motorMax - minimumValue) + minimumValue) * backwards;
	}
	return motorValue;

}

// Reads button values to modify a motor value
int motorModifiers(int motorValue)
{

	if (driver1BtnR2 || driver2BtnR2)
	{
		// R2 to slow everything down to half
		motorValue /= 2;
	}

	return motorValue;

}

// Takes a joystick value, exponents it, and applies modifiers
int fullMotorValue(int joystickValue)
{

	return motorModifiers(joystickToMotor(joystickValue));

}


task main()
{

	// Flags

	// Servo / program initialization:

	zeroEncoders();

	// Main loop:

	waitForStart();

	while (true)
	{

		getJoystickSettings(joystick);

	}

	return;

}
