#pragma config(Motor,  port2,           shoot1, tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           shoot2, tmotorNormal, openLoop)
#pragma config(Motor,  port4,           lf,     tmotorNormal, openLoop, reversed) //
#pragma config(Motor,  port5,           rf,     tmotorNormal, openLoop)           //
#pragma config(Motor,  port6,           lb,     tmotorNormal, openLoop, reversed) //
#pragma config(Motor,  port7,           rb,     tmotorNormal, openLoop)           //
#pragma config(Motor,  port8,           linear, tmotorNormal, openLoop, reversed) //
#pragma config(Motor,  port9,           scoop,  tmotorNormal, openLoop)           //
//#pragma config(Motor,  port10,          lift,   tmotorNormal, openLoop, reversed) //

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "library.c"


// Teleop-only "library" functions:
const int joystickZero = 7; // Joysticks are very sensitive; it may be a bit off zero when they're not trying to move anything anyway (out of 127)

// Exponential function to map to the joystickValue
int joystickToMotor(int joystickValue)
{

	int motorValue;
	const int minimumValue = 4; // This value high = less control, less whining; this value low = more fine control, more whining, more magic blue smoke (out of 100)
	if (abs(joystickValue) < joystickZero)
	{
		motorValue = 0;
	}
	else
	{
		// We will play the piccolo
		const int motorMax = 100;
		int backwards = joystickValue < 0 ? -1 : 1;
		motorValue = (pow(1.05, abs(joystickValue)) / pow(1.05, 127)
			* (motorMax - minimumValue) + minimumValue) * backwards;
	}
	return motorValue;

}

// Reads button values to modify a motor value
int motorModifiers(int motorValue)
{

	if (driver1BtnR2 || driver2BtnR2)
	{
		// R2 to slow everything down to half
		motorValue /= 2;
	}

	return motorValue;

}

// Takes a joystick value, exponents it, and applies modifiers
int fullMotorValue(int joystickValue)
{

	return motorModifiers(joystickToMotor(joystickValue));

}


void pre_auton()
{

	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts

}

task autonomous()
{

	//

}

task usercontrol()
{

	// Flags

	// Servo / program initialization:

	zeroEncoders();

	// Main loop:

	waitForStart();

	while (true)
	{

		getJoystickSettings(joystick);

		setLeft(100);
		setRight(100);

	}

	return;

}
